### ISSUE TITLE
[BUG] Source code is compiled with `--enable-python` indicating python support, but modpython refuses to load

### ISSUE THREAD

**Issue by vincejv** [linuxserver/docker-znc#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Loading `modpython` causes error `Unable to load modpython: Unable to open module modpython: Error loading shared library libpython3.11.so.1.0: No such file or directory (needed by /usr/lib/znc/modpython.so)`, yet in the Dockerfile support is enabled during source code compilation?
https://github.com/linuxserver/docker-znc/blob/67c4ffd671b81e19fec9943014360a94f7c1a629/Dockerfile#L70 

### Expected Behavior

Loads `modpython` without errors

### Steps To Reproduce

1. Run `/znc LoadMod modpython` in irc client
2. Error `Unable to load modpython: Unable to open module modpython: Error loading shared library libpython3.11.so.1.0: No such file or directory (needed by /usr/lib/znc/modpython.so)` shows, unable to load python module

### Environment

```markdown
- OS:Ubuntu 22.04.3 LTS
- How docker service was installed: apt, distro's package manager
```

### CPU architecture

x86-64

### Docker creation

```yaml
znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    networks:
      int-static-br:
        ipv4_address: 172.18.0.42
    volumes:
      - ./config:/config
    ports:
      - 6501:6501
      - 6588:6588
    restart: unless-stopped
```

### Container logs

```bash
Adding 1 servers... 
Loading network [p2p-network]
Loading network module [simple_away]... [/usr/lib/znc/simple_away.so]
Loading network module [stickychan]... [/usr/lib/znc/stickychan.so]
Loading network module [nickserv]... [/usr/lib/znc/nickserv.so]
Adding 1 servers... 
Loading network [rizon]
Loading network module [sasl]... [/usr/lib/znc/sasl.so]
Loading network module [simple_away]... [/usr/lib/znc/simple_away.so]
Loading network module [stickychan]... [/usr/lib/znc/stickychan.so]
Adding 1 servers... 
Loading network [superbits]
Loading network module [nickserv]... [/usr/lib/znc/nickserv.so]
Loading network module [simple_away]... [/usr/lib/znc/simple_away.so]
Loading network module [stickychan]... [/usr/lib/znc/stickychan.so]
Loading network module [perform]... [/usr/lib/znc/perform.so]
Adding 1 servers... 
Loading user module [chansaver]... 
Loading user module [controlpanel]... 
Staying open for debugging [pid: 3534]
ZNC 1.8.2 - https://znc.in
```
